- name: multipule-playbooks
  hosts: local
  tasks:
  - name: play-01 and task-01
    ansible.builtin.debug:
      msg:"Hello this paly-01 and task-01"

  - name: play-01 and task-02
    ansible.builtin.debug:
      msg:"Hello this paly-01 and task-02"

  - name: play-02 and task-01
    ansible.builtin.debug:
      msg:"Hello this paly-02 and task-01"
  
  - name: play-02 and task-02
    ansible.builtin.debug:
      msg:"Hello this paly-02 and task-02"