- name: variables in ansible
  hosts: local
  vars:
    COURSE: "linux"
    DURIATION: "120hr"
    TRAINER: "peraiah"
  tasks:
  - name: print the variables
    ansible.builtn.debug:
      msg: "course: {{ COURSE }} duriation: {{ DURIATION }} trainer: {{ task }}"