- name: conditions in ansible
  hosts: local
  connection: local
  vars:
    NUMBER: 1
  tasks:
  - name: conditions
    ansible.builtin.debug:
      msg "Given numbe {{ NUMBER }} is less than 10"
      
    when: NUMBER < 10
