- name: conditional programe
  hosts: local
  connection: local
  vars:
    NUMBER: 16
  tasks:
  - name: print the script
    ansible.builtin.debug:
      msg: echo" Given number $NUMBER is less than 20"
    when: NUMBER < 20