- name: loops in ansible
  hosts: local
  connection: local
  tasks:
  - name: print the loop data
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - peraiah
    - rambabu
    - kamesh
    - ganesh
