- name: install multiple packages
  hosts: local
  connection: local 
  become: yes
  tasks:
  - name: packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: "present"
    loop:
    - nginx
    - mysql
    - git 