- name: copying files
  hosts: local 
  connection: local
  become: yes
  tasks:
  - name: copying
    ansible.builtin.copy:
      src: 01-ping.yaml
      dest: directory
      owner: peraiah
      group: kotcherla
      mode: "0655"
