- name: creating files and directory
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: directory
    ansible.builtin.file:
      path: /home/ec2-user/preparation/room
      state: directory
  - name: file
    ansible.builtin.file:
      path: /home/ec2-user/preparation/file.text
      state: touch
