---
- name: ansible-vaults
  hosts: local
  connection: local

  vars_files:
    - secret.yaml

  tasks:
    - name: View the data
      ansible.builtin.debug:
        msg: "ADMIN: {{ admin }}, PASSWORD: {{ password }}"