- name: using rigesty command
  hosts: local
  connection: local
  tasks:
  - name: check hostname
    command: hostname
    register: peraiah

  - name: print register 
    ansible.builtin.debug:
      var: peraiah.stdout
